#!/bin/sh

vol="$(pulsemixer --get-volume | awk '{print $1}')"

if [ "$vol" -ge "70" ]; then
        icon="  "
elif [ "$vol" -lt "30" ]; then
        icon="奄  "
else
        icon="奔  "
fi

[ $(pulsemixer --get-mute) = 1 ] && icon="ﱝ  "

echo "$icon$vol%"
